CREATE TABLE TRANSACTIONS (
    TRANSACTION_ID VARCHAR(36) NOT NULL,
    TRANSACT_DATE DATE NOT NULL
);

CREATE TABLE TRANSACTION_SIDE (
    TRANSACTION_ID VARCHAR (36) NOT NULL,
    TYPE VARCHAR (8) NOT NULL,
    ACCOUNT_ID VARCHAR (36) NOT NULL,
    MONEY VARCHAR(20) NOT NULL,
    CONSTRAINT TYPE_VALUE CHECK (TYPE in ('CREDIT','DEBIT')),
    PRIMARY KEY (TRANSACTION_ID,ACCOUNT_ID),
    CONSTRAINT FK_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) REFERENCES TRANSACTIONS(TRANSACTION_ID)
);